### ISSUE TITLE
shipping tax rate bug

### ISSUE THREAD

**Issue by lankeeyankee** [lat9/edit_orders#125]
With the latest edit_orders from here with ZC 1.5.6c or 157 dev branch. In orders that have tax applied to shipping, the shipping tax rate is displaying as 0 instead of the correct tax rate. When updating another section of the order that has nothing to do with order totals, such as adding or changing address info, once you click update the sales tax is re-evaluated with 0% on the shipping unless you manually change the 0 to whatever the tax rate should be. So it seems like the tax rate is not being passed to the shipping tax rate field in edit orders.

**Comment by lat9** [comment]
You're correct, the shipping tax-rate isn't passed, per se, to EO ... EO has to _deduce_ the shipping tax-rate by interrogating the order's shipping module to see if it provides a `tax_class` variable and, if so, looks up the tax-rate based on the order's current shipping address and records that tax-rate into the order itself.

Once an order has been "run through" EO once, that tax-rate is used unless otherwise updated.

**Comment by lat9** [comment]
EO also issues a notification to allow an override of the order's shipping tax and tax-rate values:
```php
        $shipping_tax = false;
        $shipping_tax_rate = false;
        $this->notify('NOTIFY_EO_GET_ORDER_SHIPPING_TAX', $order, $shipping_tax, $shipping_tax_rate);
        if ($shipping_tax !== false && $shipping_tax_rate !== false) {
            $this->eoLog("calculateOrderShippingTax, override returning $shipping_tax, rate = $shipping_tax_rate.");
            $this->shipping_tax_rate = $shipping_tax_rate;
            return $shipping_tax;
        }
```

**Comment by lat9** [comment]
There's been a fair amount of change to EO's shipping-tax handling over the past 1+ years; please retest using the current (4.5.2 or later) version of EO.

**Comment by proseLA** [comment]
ok, rather than "just" report issues, i thought i would share my experience.  according to the config, i'm using 4.5.1 on a test site; and the re-taxing of shipping seems to work just fine.  i do not remember doing anything to EO that affects numbers at all; but the following was editing using EO and it all looks fine to me.

before:
![image](https://user-images.githubusercontent.com/1095136/102558599-a8643e00-4082-11eb-99f0-b895ee69cf14.png)

after:
![image](https://user-images.githubusercontent.com/1095136/102558639-b9ad4a80-4082-11eb-9eaa-b8f5ddd22d1c.png)
and if i just changed the shipping, and nothing else:
![image](https://user-images.githubusercontent.com/1095136/102558752-009b4000-4083-11eb-911f-1c2eb7f787d9.png)

best.

**Comment by lat9** [comment]
Thanks, @proseLA; closing.
